# Config server configuration to access the information from remote git repository
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangammelkunde/cloud-config-server

# config server port
server:
  port: 9004


# Registering config server as an eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
